export const TYPES = {
  Repository: Symbol(),
  OAuthService: Symbol(),
  PraiseRepository: Symbol(),
  PraiseService: Symbol(),
  PraisePresenter: Symbol(),
  UserRepository: Symbol(),
  UserService: Symbol(),
  UserPresenter: Symbol(),
  UserCredentialRepository: Symbol(),
  TeamRepository: Symbol(),
  TeamService: Symbol(),
  TeamPresenter: Symbol(),
  TeamPinRepository: Symbol(),
  TeamPinService: Symbol(),
  TagRepository: Symbol(),
  TagService: Symbol(),
}
